### ISSUE TITLE
It is possible to get stuck in small areas using the blue shell item.

### ISSUE THREAD

**Issue by Skillz808** [ipodtouch0218/NSMB-MarioVsLuigi#10]
It is possible to become stuck in small areas using the blue shell item.
I know this is a very small bug but I thought it might be worth sharing, even though it wouldn't easily happen in normal gameplay.

Replication Steps (easiest on ice map):
While using the blue shell item, walk towards a small gap and crouch, if you slide underneath you will become stuck.

https://user-images.githubusercontent.com/58569761/160209151-a043f0d5-d0bc-4a06-a708-b925f83c39d2.mp4

**Comment by ipodtouch0218** [comment]
Being under the spring shouldn't be a force-crouch region, so that's a separate bug, but this could still happen in one-block gaps as well.

Easiest thing would just be to allow the blue shell to accelerate while crouched, instead of defaulting back to default NSMB behavior of being pushed out by the game.

Confirmed.

**Comment by ipodtouch0218** [comment]
Fixed in release v1.5.4.0-beta
